### ISSUE TITLE
When google-cloud-key secret is missing the controller will crash loopback

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#984]
**Describe the bug**

When google-cloud-key secret is missing the controller will crash loopback.

 **Expected behavior**

Previously when the google-cloud-key is missing, the controller can enter running state.

 **To Reproduce**

Apply latest yaml.

**Log**

```
k logs controller-65d77c5b46-hgdwn -n cloud-run-events
2020/05/01 15:44:10 Registering 4 clients
2020/05/01 15:44:10 Registering 4 informer factories
2020/05/01 15:44:10 Registering 17 informers
2020/05/01 15:44:10 Registering 11 controllers
{"level":"info","ts":"2020-05-01T15:44:10.690Z","caller":"logging/config.go:111","msg":"Successfully created the logger."}
{"level":"info","ts":"2020-05-01T15:44:10.690Z","caller":"logging/config.go:112","msg":"Logging level set to info"}
{"level":"info","ts":"2020-05-01T15:44:10.691Z","caller":"logging/config.go:79","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":"2020-05-01T15:44:10.691Z","logger":"controller","caller":"profiling/server.go:59","msg":"Profiling enabled: false"}
{"level":"info","ts":"2020-05-01T15:44:10.697Z","logger":"controller","caller":"sharedmain/main.go:197","msg":"controller will not run in leader-elected mode"}
panic: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: invalid character 'd' looking for beginning of value
 
goroutine 1 [running]:
github.com/google/knative-gcp/pkg/reconciler/identity/iam.DefaultIAMPolicyManager.func1()
        github.com/google/knative-gcp/pkg/reconciler/identity/iam/iam_policy.go:84 +0x111
sync.(*Once).doSlow(0x334b8e0, 0x1e1b9f8)
        sync/once.go:66 +0xec
sync.(*Once).Do(...)
        sync/once.go:57
github.com/google/knative-gcp/pkg/reconciler/identity/iam.DefaultIAMPolicyManager(0x474e76, 0xc000a8f940)
        github.com/google/knative-gcp/pkg/reconciler/identity/iam/iam_policy.go:81 +0x65
github.com/google/knative-gcp/pkg/reconciler/events/auditlogs.NewController(0x21114a0, 0xc0006a2330, 0x20e5a20, 0xc00080a000, 0x1c6b040)
        github.com/google/knative-gcp/pkg/reconciler/events/auditlogs/controller.go:63 +0x22
knative.dev/pkg/injection/sharedmain.ControllersAndWebhooksFromCtors(0x21114a0, 0xc0006a2330, 0xc00080a000, 0xc0001351a0, 0xb, 0xb, 0x32fe3a0, 0xc0000def00, 0x2, 0xc000a8fc00, ...)
        knative.dev/pkg/injection/sharedmain/main.go:405 +0x135
knative.dev/pkg/injection/sharedmain.MainWithConfig.func2(0x21114a0, 0xc0006a2330)
        knative.dev/pkg/injection/sharedmain/main.go:171 +0xe6
knative.dev/pkg/injection/sharedmain.MainWithConfig(0x2112260, 0xc000537168, 0x1d60f28, 0xa, 0xc000182600, 0xc0001351a0, 0xb, 0xb)
        knative.dev/pkg/injection/sharedmain/main.go:198 +0xaba
knative.dev/pkg/injection/sharedmain.MainWithContext(0x2112260, 0xc000537168, 0x1d60f28, 0xa, 0xc0001351a0, 0xb, 0xb)
        knative.dev/pkg/injection/sharedmain/main.go:130 +0x78
knative.dev/pkg/injection/sharedmain.Main(0x1d60f28, 0xa, 0xc0001351a0, 0xb, 0xb)
        knative.dev/pkg/injection/sharedmain/main.go:124 +0x9c
main.main()
        github.com/google/knative-gcp/cmd/controller/main.go:41 +0xe3
```

**Comment by yolocs** [comment]
Close as it cannot be reproduced.
